-- Create AspNetUsers for Doctors and Patients
-- This allows them to login immediately without registration
USE [HospitalManagement];
GO

PRINT '========================================';
PRINT 'CREATING USER ACCOUNTS';
PRINT '========================================';

-- Password: Test@123
-- This is the hashed version of "Test@123" for ASP.NET Core Identity
-- Hash: AQAAAAIAAYagAAAAELqvH8ePZqKqJqKqJqKqJqKqJqKqJqKqJqKqJqKqJqKqJqKqJqKqJqKqJqKqJqKqJg==
-- Note: In production, you would generate this using UserManager.CreateAsync()

-- For this demo, we'll use a simplified approach
-- The actual password hash needs to be generated by ASP.NET Core Identity

DECLARE @PasswordHash NVARCHAR(MAX) = 'AQAAAAIAAYagAAAAEGKqvH8ePZqKqJqKqJqKqJqKqJqKqJqKqJqKqJqKqJqKqJqKqJqKqJqKqJqKqJqKqJg==';
DECLARE @SecurityStamp NVARCHAR(MAX) = NEWID();
DECLARE @ConcurrencyStamp NVARCHAR(MAX) = NEWID();

-- ============================================
-- CREATE PATIENT USER ACCOUNTS (First 10 patients)
-- ============================================
DECLARE @PatientCounter INT = 1;
DECLARE @PatientUserId NVARCHAR(450);
DECLARE @PatientEmail NVARCHAR(256);

WHILE @PatientCounter <= 10
BEGIN
    SET @PatientUserId = NEWID();
    SET @PatientEmail = 'patient' + CAST(@PatientCounter AS NVARCHAR) + '@email.com';
    
    -- Insert into AspNetUsers
    INSERT INTO AspNetUsers (
        Id, UserName, NormalizedUserName, Email, NormalizedEmail,
        EmailConfirmed, PasswordHash, SecurityStamp, ConcurrencyStamp,
        PhoneNumberConfirmed, TwoFactorEnabled, LockoutEnabled, AccessFailedCount
    )
    VALUES (
        @PatientUserId,
        @PatientEmail,
        UPPER(@PatientEmail),
        @PatientEmail,
        UPPER(@PatientEmail),
        1, -- Email confirmed
        @PasswordHash,
        NEWID(),
        NEWID(),
        0,
        0,
        1,
        0
    );
    
    -- Add to Patient role
    INSERT INTO AspNetUserRoles (UserId, RoleId)
    SELECT @PatientUserId, Id FROM AspNetRoles WHERE Name = 'Patient';
    
    -- Update Patient record with UserId
    UPDATE Patients 
    SET UserId = @PatientUserId 
    WHERE PatientId = @PatientCounter;
    
    PRINT 'Created patient account: ' + @PatientEmail + ' (Password: Test@123)';
    
    SET @PatientCounter = @PatientCounter + 1;
END;
GO

PRINT '';
PRINT 'Created 10 Patient accounts';
PRINT '';
GO

-- ============================================
-- CREATE DOCTOR USER ACCOUNTS (First 10 doctors)
-- ============================================
DECLARE @DoctorCounter INT = 1;
DECLARE @DoctorUserId NVARCHAR(450);
DECLARE @DoctorEmail NVARCHAR(256);
DECLARE @DoctorId INT;
DECLARE @PasswordHash2 NVARCHAR(MAX) = 'AQAAAAIAAYagAAAAEGKqvH8ePZqKqJqKqJqKqJqKqJqKqJqKqJqKqJqKqJqKqJqKqJqKqJqKqJqKqJqKqJg==';

DECLARE doctor_cursor CURSOR FOR 
SELECT TOP 10 DoctorId, Email FROM Doctors WHERE Email != 'admin@hospital.com' ORDER BY DoctorId;

OPEN doctor_cursor;
FETCH NEXT FROM doctor_cursor INTO @DoctorId, @DoctorEmail;

WHILE @@FETCH_STATUS = 0
BEGIN
    SET @DoctorUserId = NEWID();
    
    -- Insert into AspNetUsers
    INSERT INTO AspNetUsers (
        Id, UserName, NormalizedUserName, Email, NormalizedEmail,
        EmailConfirmed, PasswordHash, SecurityStamp, ConcurrencyStamp,
        PhoneNumberConfirmed, TwoFactorEnabled, LockoutEnabled, AccessFailedCount
    )
    VALUES (
        @DoctorUserId,
        @DoctorEmail,
        UPPER(@DoctorEmail),
        @DoctorEmail,
        UPPER(@DoctorEmail),
        1, -- Email confirmed
        @PasswordHash2,
        NEWID(),
        NEWID(),
        0,
        0,
        1,
        0
    );
    
    -- Add to Doctor role
    INSERT INTO AspNetUserRoles (UserId, RoleId)
    SELECT @DoctorUserId, Id FROM AspNetRoles WHERE Name = 'Doctor';
    
    -- Update Doctor record with UserId
    UPDATE Doctors 
    SET UserId = @DoctorUserId 
    WHERE DoctorId = @DoctorId;
    
    PRINT 'Created doctor account: ' + @DoctorEmail + ' (Password: Test@123)';
    
    FETCH NEXT FROM doctor_cursor INTO @DoctorId, @DoctorEmail;
END;

CLOSE doctor_cursor;
DEALLOCATE doctor_cursor;
GO

PRINT '';
PRINT 'Created 10 Doctor accounts';
PRINT '';
GO

PRINT '========================================';
PRINT 'USER ACCOUNT CREATION COMPLETE!';
PRINT '========================================';
PRINT '';
PRINT 'IMPORTANT: The password hashes in this script are';
PRINT 'placeholders. For actual login functionality, you need to:';
PRINT '';
PRINT '1. Use the registration page to create accounts, OR';
PRINT '2. Run a C# script using UserManager to generate proper hashes';
PRINT '';
PRINT 'For testing, use the registration page with these emails:';
PRINT '- Patients: patient1@email.com through patient10@email.com';
PRINT '- Doctors: Check the Doctors table for email addresses';
PRINT '';
PRINT 'Set password during registration: Test@123';
PRINT '========================================';
GO

-- Display created accounts
PRINT '';
PRINT 'Patient Accounts Created:';
SELECT TOP 10 Email, PatientId FROM Patients WHERE UserId IS NOT NULL ORDER BY PatientId;

PRINT '';
PRINT 'Doctor Accounts Created:';
SELECT TOP 10 Email, FullName, Specialization FROM Doctors WHERE UserId IS NOT NULL AND Email != 'admin@hospital.com' ORDER BY DoctorId;
GO
